version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis_alert_system
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

    volumes:
      - redis_data:/data


  redis_ui:
    image: redis/redisinsight:latest
    container_name: redis_ui_alert_system
    ports:
      - '5540:5540'
    depends_on:
      - redis


  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: mongo_alert_system
    restart: always
    ports:
      - '27017:27017'

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: 'alerts'

    volumes:
      - mongo_data:/data/db


  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile

    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'

    depends_on:
      redis:
        condition: service_healthy


  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile

    environment:
      MONGO_COLLECTION: 'alerts'
      MONGO_DATABASE: 'alerts'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/?authSource=admin'

      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'

    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy


  api:
    build:
      context: analytics_api
      dockerfile: Dockerfile

    environment:
      MONGO_COLLECTION: 'alerts'
      MONGO_DATABASE: 'alerts'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/?authSource=admin'


volumes:
  mongo_data:
  redis_data: